menu_exp/urls.py
from django.conf.urls import url
from django.contrib import admin
import restaurants.views 
import menu_exp.views
from django.contrib.auth.views import login,logout

from menu_exp.views import Index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^menu/(\d{1,5})/$',restaurants.views.menu),
    url(r'^meta/$',restaurants.views.meta),
    url(r'^welcome/$',menu_exp.views.welcome),
    url(r'^restaurants_list/$',restaurants.views.list_restaurants),
    url(r'^comment/(\d{1,5})/$',restaurants.views.comment),
    #url(r'^set_c/$',restaurants.views.set_c),
    #url(r'^get_c/$',restaurants.views.get_c),
    #url(r'^session/$',restaurants.views.use_session),
    #url(r'^t_session/$',restaurants.views.test_session),
    url(r'^accounts/login/$',login),
 #   url(r'^index/$',menu_exp.views.index),
    url(r'^index/$',Index.as_view()) ,
    url(r'register/$',menu_exp.views.register),
    url(r'^accounts/logout/$',logout)

]

restaurants/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
	name = models.CharField(max_length = 20)
	phone_number = models.CharField(max_length = 15)
	address = models.CharField(max_length = 50, blank = True)
	open_date = models.DateField(blank = True, null = True)
	def __str__(self):
		return self.name
	class Meta:
		ordering = ['name']


class Food(models.Model):
	name = models.CharField(max_length = 20)
	price = models.DecimalField(max_digits = 3,decimal_places = 0)
	comment = models.CharField(max_length = 50, blank = True)
	is_spicy = models.BooleanField(default = False)
	restaurant = models.ForeignKey(Restaurant)
	def __str__(self):
		return self.name
	class Meta:
		ordering = ['price']

class Comment(models.Model):
	visitor = models.CharField(max_length = 255)
	content = models.CharField(max_length = 255)
	email = models.EmailField(max_length = 255)
	date_time = models.DateTimeField()
	restaurant = models.ForeignKey(Restaurant)
	class Meta:
		ordering = ['date_time']
		permissions = (
				('see_comment','Can only see comments'),
				
			)

menu_exp/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(max_length = 20)
	password = forms.CharField(max_length = 20)

class  RegisterForm(forms.Form):
	username = forms.CharField(max_length = 20)
	password = forms.CharField(max_length = 20)
	email = forms.EmailField()
	
	

restaurants/forms.py
from django import forms

class  CommentForm(forms.Form):
	"""docstring for  CommentForm"""
	visitor = forms.CharField(max_length = 20)
	email = forms.EmailField(max_length = 20,required = False)
	content = forms.CharField(max_length = 200, widget = forms.Textarea())
	def clean_content(self):
		content = self.cleaned_data['content']
		if ('幹' in content):
			raise forms.ValidationError('請勿使用不雅文字')

		return content

menu_exp/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render_to_response,render
from django.contrib import auth
#from menu_exp.forms import LoginForm,RegisterForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Permission,Group,User

from django.views.generic.base import View,TemplateView

def welcome(request):
	if ('user_name' in request.GET) and (request.GET.get('user_name','') != ''):
		return HttpResponse('Welcome!~'+request.GET.get('user_name'))
	else:
		return render_to_response('welcome.html',locals())
'''
def login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/index/')
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')

		user = auth.authenticate(username = username ,password =password)
		if (user is not None) and (user.is_active):
			auth.login(request,user)
			return HttpResponseRedirect('/index/')
		else:
			f = LoginForm()
			c = locals()
			return render(request,'login.html',c)
	else:
			f = LoginForm()
			c = locals()
			return render(request,'login.html',c)
'''
def register(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			return HttpResponseRedirect('/accounts/login/')
		else:
			form = UserCreationForm()
			return render(request,'register.html',locals())
	else:
		form = UserCreationForm()
		return render(request,'register.html',locals())
'''
class  Index(TemplateView):
	template_name =  'index.html'
	def get(self,request,*args,**kwargs):
		context = self.get_context_data(**kwargs)
		context['request'] = request
		context['really'] = '真的假的'
		return self.render_to_response(context)
'''


'''

def index(request):
	if request.user.is_authenticated():
		g = Group.objects.get(name = 'see_comment_group')
	#	perm2 = Permission.objects.get(codename = 'add_comment')
		request.user.groups.add(g)
	return render(request,'index.html',locals())
'''
'''
def register(request):
	if (request.method == "POST") and (request.POST.get('username','') != '') and (request.POST.get('password','') != ''):
		un = request.POST['username']
		pw = request.POST['password']
		new_user = User.objects.create(username = un, password = pw)
		new_user.set_password(pw)
		new_user.save()
		return HttpResponseRedirect('/accounts/login/')
	else:
		f = RegisterForm(request.POST)
		return render(request,'register.html',locals())

def logout(request):
	auth.logout(request)
	return HttpResponseRedirect('/index/')
'''

restaurants/views.py
from django.shortcuts import render,render_to_response
import datetime
from django.http import HttpResponse
from restaurants.models import Restaurant,Food,Comment
from django.utils import timezone
from django.template import RequestContext
from restaurants.forms import CommentForm
from django.contrib.sessions.models import Session
from django.contrib.auth.decorators import login_required,permission_required

@login_required
def menu(request,id):
	if id:
		r = Restaurant.objects.get(id = id)
		path = request.path
		return render_to_response('menu.html',locals())
	else:
		return HttpResponseRedirect('/restaurants_list/')

def meta(request):
	values = request.META.items()
	html = []
	for k,v in values:
		html.append('<tr><td>{0}</td><td>{1}</td></tr>'.format(k,v))
	return HttpResponse('<table>{0}</table>'.format('\n'.join(html)))


@login_required
def list_restaurants(request):
	restaurants = Restaurant.objects.all()
	request.session['restaurant'] = restaurants
	return render(request,'restaurants_list.html',locals())

@permission_required('restaurants.see_comment')
def comment(request,id):
	if id:
		r = Restaurant.objects.get(id = id)
	else:
		return HttpResponseRedirect('/restaurants_list/')
	if request.POST:
		f = CommentForm(request.POST)

		if f.is_valid():
			visitor = f.cleaned_data['visitor']
			email  = f.cleaned_data['email']
			content = f.cleaned_data['content']
			date_time = datetime.datetime.now()
			Comment.objects.create(
					visitor = visitor,
					email = email,
					content = content,
					date_time = date_time,
					restaurant = r
				)
			f = CommentForm(initial = {'visitor':'我是丁丁'})
	else:
		f = CommentForm(initial ={'content':'好吃阿!'})
	c=locals()
	return render(request,'comments.html',c)
#	return render_to_response('comments.html',RequestContext(request,locals()))

def set_c(request):
	response = HttpResponse('設定幸運數字為八')
	response.set_cookie('lunky_number',8)
#	response.set_cookie('try',4)
	return response


def get_c(request):
	if 'lunky_number' in request.COOKIES:
		return HttpResponse('Your lunky_number is {0}'.format(request.COOKIES.get('lunky_number','error')))

	else:
		return HttpResponse('No cookie')

def use_session(request):
	request.session['lucky'] = 10
	if 'lucky' in request.session:
		lucky = request.session['lucky']
		response = HttpResponse('Your lucky is {0}'.format(lucky))
#	del request.session['lucky']
	return response
def test_session(request):
	sid = request.COOKIES['sessionid']
	s = Session.objects.get(pk = sid)
	s_infro = 'ID:' + sid + '<br>Expire date:' + str(s.expire_date)+ '<br>Data:' + str(s.get_decoded())
	return HttpResponse(s_infro)

restaurants/templates/comments.html
<!DOCTYPE html>
<html>
<head>
	<title>Comment</title>
</head>
<body>
	<h2>{{ r.name }}的評價</h2>
	{% if r.comment_set.all %}
	<p>目前共有{{ r.comment_set.all|length }}條評價</p>
	<table class = "table">
		<tr>
			<th>留言者</th>
			<th>時間</th>
			<th>內容</th>
		</tr>
		{% for c in r.comment_set.all %}
		<tr>
			<td>{{ c.visitor }}</td>
			<td>{{ c.date_time | date:"F j, Y"}}</td>
			<td>{{ c.content }}</td>
		</tr>
		{% endfor %}
	</table>
	{% else %}
	<p>沒有任何評價</p>
	{% endif %}
{% if perms.restaurants.add_comment %}
	<br>
	<br>
	<form action = "" method="post" >
	 {% csrf_token %}
		<table class="table">
			<tr>
				<th><label for="id_visitor">留言者:</label></th>
				<td>{{ f.visitor }}</td>
				<td>{{ f.visitor.errors }}</td>
			</tr>
			<tr>
				<th><label for="id_email">電子信箱:</label></th>
				<td>{{ f.email }}</td>
				<td>{{ f.email.errors }}</td>
			</tr>
			<tr>
				<th><label for="id_visitor">評論內容:</label></th>
				<td>{{ f.content }}</td>
				<td>{{ f.content.errors }}</td>
			</tr>
		</table>
		<input type="submit" value="給予評價">
	
	</form>
{% endif %}
</body>
</html>

restaurants/templates/menu.html
<!DOCTYPE html>
<html>
<head>
	<title>Menu</title>
	<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
	<style>
		th { text-align :center; }
		div.menus {
			text-align: center;
			padding :40px 15px;
		}
	</style>
</head>
<body>
<p>您現在在{{ path }}</p>
{% comment %}
可以加入上方導航列的bootstrap
{% endcomment %}
<div class = "container">
<div class = "menus">
<p>
<h2>{{ r.name }}的Menu</h2>
{% if r.food_set.all %}
<p>本餐廳共有{{ r.food_set.all|length }}道菜</p>
<table class = "table">
	<tr>
		<th>菜名</th>
		<th>價格</th>
		<th>辣不辣</th>
		<th>註解</th>
	</tr>
	{% for f in r.food_set.all %}
	<tr>
		<td>{{ f.name }}</td>
		<td>{{ f.price }}</td>
		{%　if f.is_spicy %}
		<td>辣</td>
		{% else %}
		<td>不辣</td>
		{% endif %}
		<td>{{ f.comment }}</td>

	</tr>
	{% endfor %}
</table>
</p>
{% else %}
<p>本餐廳啥都沒賣</p>
{% endif %}

</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

restaurants/templates/restaurants_list.html
<!DOCTYPE html>
<html>
<head>
	<title>Restaurants</title>
	<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
	<style>
		th { text-align :center; }
		div.list {
			text-align: center;
			padding :40px 15px;
		}
	</style>
</head>
<body>
<div class = "container">
<div class = "list">
	<h2>餐廳列表</h2>
	
	<table class = "table">
		<tr>
			<th>觀看menu</th>
			<th>店名</th>
			<th>電話</th>
			<th>地址</th>
			{% if perms.restaurants.see_comment %}
			<th>評價</th>
			{% endif %}
		</tr>
		{% for r in restaurants %}
		<tr>
			<td><a href="/menu/{{ r.id }}/">menu</a></td>
			<td>{{ r.name }}</td>
			<td>{{ r.phone_number }}</td>
			<td>{{ r.address }}</td>	
			{% if perms.restaurants.see_comment %}
			<td><a href="/comment/{{r.id}}">comment</a></td>
			{% endif %}		
		</tr>
		{% endfor %}
		
	</table>
	
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Restaurant King</title>
</head>
<body>
	<h2>歡迎來到餐廳王</h2>
	<h1>{{ really }}</h1>
	{% if request.user.is_authenticated %}
	<p>{{ request.user }}您已經登入摟</p>
	<p><a href="/accounts/logout/">登出</a></p>
	<p><a href="/restaurants_list/">進入餐廳列表</a></p>
	{%else%}
	<p>您尚未登入<a href="/accounts/login/">登入</a></p>
	<p><a href="/register/">註冊新帳號</a></p>
	{% endif %}

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
</head>
<body>
	<form method="post" action="">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="註冊">
		
	</form>

</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	<form action = "/welcome/", method="get">
		<label for = "user_name">您的名字</label>
		<input type="text" name="user_name" id="user_name">
		<input type="submit" value="進入網站">
		
	</form>

</body>
</html>